//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Fahrt = new HashSet<Fahrt>();
            this.Reservierung = new HashSet<Reservierung>();
            this.Tanksaeule = new HashSet<Tanksaeule>();
        }
    
        public int Car_ID { get; set; }
        public string Seriennummer { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<bool> Gesperrt { get; set; }
        public Nullable<bool> SpontaneNutzungGesperrt { get; set; }
        public Nullable<bool> ReservierungGesperrt { get; set; }
        public int Tankvorgaenge { get; set; }
        public Nullable<double> Kilometerstand { get; set; }
        public Nullable<int> Batterieladung { get; set; }
        public Nullable<System.DateTime> Wartungstermin { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual ICollection<Fahrt> Fahrt { get; set; }
        public virtual ICollection<Reservierung> Reservierung { get; set; }
        public virtual ICollection<Tanksaeule> Tanksaeule { get; set; }
    }
}
