//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrt
    {
        public int Fahrt_ID { get; set; }
        public int Abholort { get; set; }
        public int Abgabeort { get; set; }
        public Nullable<System.DateTime> Startzeit { get; set; }
        public Nullable<System.DateTime> Endzeit { get; set; }
        public Nullable<double> Start_KM { get; set; }
        public Nullable<double> End_KM { get; set; }
        public Nullable<int> Car_ID { get; set; }
        public Nullable<int> Kunde_ID { get; set; }
        public Nullable<int> Reservierung_ID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Tanksaeule Tanksaeule { get; set; }
        public virtual Tanksaeule Tanksaeule1 { get; set; }
        public virtual Kunde Kunde { get; set; }
        public virtual Reservierung Reservierung { get; set; }
    }
}
