//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karte
    {
        public int Karten_ID { get; set; }
        public int Kunde_ID { get; set; }
        public bool Aktiv { get; set; }
        public Nullable<System.DateTime> Sperrdatum { get; set; }
        public string Sperrvermerk { get; set; }
    
        public virtual Kunde Kunde { get; set; }
    }
}
