//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        public Kunde()
        {
            this.Fahrt = new HashSet<Fahrt>();
            this.Karte = new HashSet<Karte>();
            this.Rechnung = new HashSet<Rechnung>();
            this.Reservierung = new HashSet<Reservierung>();
        }
    
        public int Kunde_ID { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Passwort { get; set; }
        public int Adress_ID { get; set; }
        public Nullable<int> RechnungAdr_ID { get; set; }
        public int Bank_ID { get; set; }
        public bool Gesperrt { get; set; }
        public string Email { get; set; }
        public byte[] FKopie { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual ICollection<Fahrt> Fahrt { get; set; }
        public virtual ICollection<Karte> Karte { get; set; }
        public virtual Kunde Kunde1 { get; set; }
        public virtual Kunde Kunde2 { get; set; }
        public virtual ICollection<Rechnung> Rechnung { get; set; }
        public virtual ICollection<Reservierung> Reservierung { get; set; }
    }
}
