//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnung
    {
        public int Rechnung_ID { get; set; }
        public int Kunden_ID { get; set; }
        public double Betrag { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Kunde Kunde { get; set; }
    }
}
