//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Car1 = new HashSet<Car>();
        }
    
        public int Status_ID { get; set; }
        public Nullable<System.DateTime> Wartungstermin { get; set; }
        public Nullable<int> Baterieladung { get; set; }
        public Nullable<double> KM_Stand { get; set; }
        public string Standort { get; set; }
        public Nullable<System.DateTime> StatusZeit { get; set; }
        public Nullable<int> Car { get; set; }
    
        public virtual ICollection<Car> Car1 { get; set; }
        public virtual Car Car2 { get; set; }
    }
}
