//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tankstelle
    {
        public Tankstelle()
        {
            this.Reservierung = new HashSet<Reservierung>();
            this.Tanksaeule = new HashSet<Tanksaeule>();
        }
    
        public int Tankstelle_ID { get; set; }
        public Nullable<double> breitengrad { get; set; }
        public Nullable<double> laengengrad { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Stasse { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Reservierung> Reservierung { get; set; }
        public virtual ICollection<Tanksaeule> Tanksaeule { get; set; }
    }
}
